# Makefile

# Variables
CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2

# Targets
TARGET_SELECTION = Selectionsort
TARGET_MERGE = Mergesort
TARGET_QUICK = Quicksort
TARGET_DEFAULT = Csort
TARGET_ITERATIVO_TRADICIONAL = IterativoCubicoTradicional
TARGET_ITERATIVO_OPTIMIZADO = IterativoCubicoOptimizado
TARGET_STRASSEN = Strassen

# Source files
SRC_SELECTION = Selectionsort.cpp
SRC_MERGE = Mergesort.cpp
SRC_QUICK = Quicksort.cpp
SRC_DEFAULT = Csort.cpp
SRC_ITERATIVO_TRADICIONAL = IterativoCubicoTradicional.cpp
SRC_ITERATIVO_OPTIMIZADO = IterativoCubicoOptimizado.cpp
SRC_STRASSEN = Strassen.cpp

# Rules
all: $(TARGET_SELECTION) $(TARGET_MERGE) $(TARGET_QUICK) $(TARGET_DEFAULT) $(TARGET_ITERATIVO_TRADICIONAL) $(TARGET_ITERATIVO_OPTIMIZADO) $(TARGET_STRASSEN)

$(TARGET_SELECTION): $(SRC_SELECTION)
	$(CXX) $(CXXFLAGS) $(SRC_SELECTION) -o $(TARGET_SELECTION)

$(TARGET_MERGE): $(SRC_MERGE)
	$(CXX) $(CXXFLAGS) $(SRC_MERGE) -o $(TARGET_MERGE)

$(TARGET_QUICK): $(SRC_QUICK)
	$(CXX) $(CXXFLAGS) $(SRC_QUICK) -o $(TARGET_QUICK)

$(TARGET_DEFAULT): $(SRC_DEFAULT)
	$(CXX) $(CXXFLAGS) $(SRC_DEFAULT) -o $(TARGET_DEFAULT)

$(TARGET_ITERATIVO_TRADICIONAL): $(SRC_ITERATIVO_TRADICIONAL)
	$(CXX) $(CXXFLAGS) $(SRC_ITERATIVO_TRADICIONAL) -o $(TARGET_ITERATIVO_TRADICIONAL)

$(TARGET_ITERATIVO_OPTIMIZADO): $(SRC_ITERATIVO_OPTIMIZADO)
	$(CXX) $(CXXFLAGS) $(SRC_ITERATIVO_OPTIMIZADO) -o $(TARGET_ITERATIVO_OPTIMIZADO)

$(TARGET_STRASSEN): $(SRC_STRASSEN)
	$(CXX) $(CXXFLAGS) $(SRC_STRASSEN) -o $(TARGET_STRASSEN)

clean:
	rm -f $(TARGET_SELECTION) $(TARGET_MERGE) $(TARGET_QUICK) $(TARGET_DEFAULT) $(TARGET_ITERATIVO_TRADICIONAL) $(TARGET_ITERATIVO_OPTIMIZADO) $(TARGET_STRASSEN)
